# Development overrides for Docker Compose
version: '3.8'

services:
  node-1:
    environment:
      - DEBUG=true
      - NEXUS_ENVIRONMENT=development
    volumes:
      # Mount source code for development
      - ../docker/scripts:/app/scripts:ro
      - ../docker/config:/app/config:ro
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

  node-2:
    environment:
      - DEBUG=true
      - NEXUS_ENVIRONMENT=development
    volumes:
      - ../docker/scripts:/app/scripts:ro
      - ../docker/config:/app/config:ro
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

  node-3:
    environment:
      - DEBUG=true
      - NEXUS_ENVIRONMENT=development
    volumes:
      - ../docker/scripts:/app/scripts:ro
      - ../docker/config:/app/config:ro
    ports:
      - "8083:8080"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

  multi-node:
    environment:
      - DEBUG=true
      - NEXUS_ENVIRONMENT=development
    volumes:
      - ../docker/scripts:/app/scripts:ro
      - ../docker/config:/app/config:ro
    ports:
      - "8090:8080"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 1G
